import pyarrow as pa

schema = pa.schema([
    pa.field("adid", pa.float64()),
    pa.field("amplitude_attribution_ids", pa.list_(pa.null())),
    pa.field("amplitude_event_type", pa.float64()),
    pa.field("amplitude_id", pa.int64()),
    pa.field("app", pa.int64()),
    pa.field("city", pa.string()),
    pa.field("client_event_time", pa.timestamp('us', tz='UTC')),
    pa.field("client_upload_time", pa.timestamp('us', tz='UTC')),
    pa.field("country", pa.string()),
    pa.field("data", pa.string()),
    pa.field("device_brand", pa.float64()),
    pa.field("device_carrier", pa.float64()),
    pa.field("device_family", pa.string()),
    pa.field("device_id", pa.string()),
    pa.field("device_manufacturer", pa.float64()),
    pa.field("device_model", pa.float64()),
    pa.field("device_type", pa.string()),
    pa.field("event_id", pa.int64()),
    pa.field("event_properties", pa.string()),
    pa.field("event_time", pa.timestamp('us', tz='UTC')),
    pa.field("event_type", pa.string()),
    pa.field("followed_an_identify", pa.float64()),
    pa.field("group_properties", pa.string()),
    pa.field("groups", pa.string()),
    pa.field("idfa", pa.float64()),
    pa.field("ip_address", pa.string()),
    pa.field("is_attribution_event", pa.float64()),
    pa.field("language", pa.string()),
    pa.field("library", pa.string()),
    pa.field("location_lat", pa.float64()),
    pa.field("location_lng", pa.float64()),
    pa.field("os_name", pa.string()),
    pa.field("os_version", pa.string()),
    pa.field("paying", pa.float64()),
    pa.field("platform", pa.string()),
    pa.field("processed_time", pa.timestamp('us', tz='UTC')),
    pa.field("region", pa.string()),
    pa.field("sample_rate", pa.float64()),
    pa.field("server_received_time", pa.timestamp('us', tz='UTC')),
    pa.field("server_upload_time", pa.timestamp('us', tz='UTC')),
    pa.field("session_id", pa.int64()),
    pa.field("start_version", pa.float64()),
    pa.field("user_creation_time", pa.timestamp('us')),
    pa.field("user_id", pa.float64()),
    pa.field("user_properties", pa.string()),
    pa.field("uuid", pa.string()),
    pa.field("version_name", pa.float64()),
])